import React from 'react';
import './FAQPage.css'; // We will update this file next
import { Link } from 'react-router-dom';
import { MessageSquare } from 'lucide-react'; // Import the icon for the help card

// This is a simple data structure for our Q&A pairs
const faqData = [
  {
    question: 'How does the community valuation work?',
    answer:
      'Users vote whether a property is undervalued, fairly priced, or overvalued. The votes are aggregated and displayed as percentages to help you gauge community sentiment.',
  },
  {
    question: 'What does "fair-valued" / "over-valued" / "under-valued" mean?',
    answer:
      'This is a valuation generated by our AI model. "Fair-valued" means the price is within the expected range, "over-valued" means the price is higher than our model\'s estimate, and "under-valued" means the price is lower than our estimate. This is for informational purposes only.',
  },
  {
    question: 'How do I search for a resale flat in a specific town?',
    answer:
      'You can use the "Search" link in the navigation bar to go to our advanced search page. Alternatively, on the homepage map, you can use the filter controls to select a town, which will automatically update the properties shown on the map.',
  },
  {
    question: 'Where can I find my saved (bookmarked) properties?',
    answer:
      'If you are logged in, you can click the "Bookmarks" link in the navigation bar. This will take you to a dedicated page showing all the properties you have saved.',
  },
  {
    question: 'How does the "Compare" feature work?',
    answer:
      'On any property card (on the map or search page) or on a detailed insights page, click the "Compare" button. This adds the property to your "Comparison Basket" at the bottom of the screen. You can add up to 4 properties and then click "Compare" in the basket to see a side-by-side table.',
  },
  {
    question: 'Can I share a property\'s insights with someone?',
    answer:
      'Yes! On the "Detailed Insights View" for any property, there is a "Share" button at the top. Clicking this will copy the direct URL for that page to your clipboard, allowing you to paste it and send it to anyone.',
  },
  {
    question: 'How accurate are the price predictions?',
    answer:
      'Our ML models use historical data and current market trends with the Gradient Boosting Regressor to achieve satisfactory results (RMSE: $17,815, R-squared: 98.66%) for HDB resale price prediction compare to normal base model (Linear Regression) results (RMSE: $35,954, R-squared: 94.54%). However, actual prices can vary based on market conditions.',
  },
  {
    question: 'What amenities data is included?',
    answer:
      'We track nearby schools, MRT stations, shopping centers, parks, and other important facilities. Distance and count are calculated from the property location.',
  },
  {
    question: 'How often is the property data updated?',
    answer:
      'Property data is sourced from official HDB records and updated monthly to ensure you have the latest information.',
  },
  {
    question: 'Can I compare more than 3 properties?',
    answer:
      'Currently, the comparison feature supports up to 3 properties at once for optimal visualization. You can clear your selection and compare different sets.',
  },
];

const FAQPage: React.FC = () => {
  return (
    <div className="page-container faq-page">
      <h1 className="support-center-title">Support Center</h1>
      <h2 className="faq-header">Frequently Asked Questions</h2>

      <div className="faq-list">
        {faqData.map((item, index) => (
          <div key={index} className="faq-item card">
            <h3 className="faq-question">{item.question}</h3>
            <p className="faq-answer">{item.answer}</p>
          </div>
        ))}
      </div>

      {/* --- "Need More Help?" Card --- */}
      <div className="help-card">
        <MessageSquare size={48} className="help-card-icon" />
        <div className="help-card-content">
          <h2 className="help-card-title">Need More Help?</h2>
          <p className="help-card-text">
            Can't find what you're looking for? Our customer support team is here to help! Chat with us live
            and get instant answers to your questions.
          </p>
          {/* This links to your project's existing customer support page */}
          <Link to="/customer-support" className="button help-card-button">
            <MessageSquare size={20} style={{ marginRight: '0.5rem' }} />
            Start Live Chat
          </Link>
          <p className="help-card-footer-text">
            Available Monday - Friday, 9 AM - 6 PM SGT
            <br />
            Average response time: Under 2 minutes
          </p>
        </div>
      </div>

      {/* --- "Other Ways to Reach Us" Section --- */}
      <div className="other-reach-out">
        <h3 className="other-reach-out-title">Other Ways to Reach Us</h3>
        <div className="other-reach-out-links">
          <div className="other-reach-out-item">
            <strong>Email:</strong>
            <a href="mailto:support@resalesense.com">support@resalesense.com</a>
          </div>
          <div className="other-reach-out-item">
            <strong>Phone:</strong>
            <a href="tel:+6512345678">+65 1234 5678</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQPage;